export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const SET_PRODUCTS_CHILDREN = 'SET_PRODUCTS_CHILDREN';
export const SET_PRODUCTS_WOMEN = 'SET_PRODUCTS_WOMEN';
export const SET_PRODUCTS_MEN = 'SET_PRODUCTS_MEN';
export const SET_SHOPPING = 'SET_SHOPPING';
